### ISSUE TITLE
$signature not match to $hash

### ISSUE THREAD

**Issue by JamesKid** [mdluo/github-webhook-handler-php#1]
$signature not match to $hash,then it can't go pass the "if(strcmp($signature,$hash)==0) " ,why
![git](https://cloud.githubusercontent.com/assets/6158899/10410281/8a0158c4-6f6f-11e5-9fbd-0075ca68639f.jpg)
![Uploading git2.png…]()

**Comment by mdluo** [comment]
$secret must be exactly the same with the one one your github/repository/settings/webhooks page.
You can edit the code and send a test delivery on that page to get your $signature and $hash

**Comment by JamesKid** [comment]
i get the proble ,that i set content type to 'x-www-form-urlencode' ,then i set it to 'application/json' that run  right many thanks !
